// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: multiChat.proto
// Protobuf Java Version: 4.29.0

package com.example.grpc.multiChat;

public final class MultiChat {
  private MultiChat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      MultiChat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_multiChat_MultiChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_multiChat_MultiChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017multiChat.proto\022\032com.example.grpc.mult" +
      "iChat\"F\n\020MultiChatMessage\022\016\n\006sender\030\001 \001(" +
      "\t\022\017\n\007message\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t2\201\001" +
      "\n\020MultiChatService\022m\n\013SendMessage\022,.com." +
      "example.grpc.multiChat.MultiChatMessage\032" +
      ",.com.example.grpc.multiChat.MultiChatMe" +
      "ssage(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_multiChat_MultiChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_multiChat_MultiChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_multiChat_MultiChatMessage_descriptor,
        new java.lang.String[] { "Sender", "Message", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
