// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat.proto
// Protobuf Java Version: 4.29.0

package com.example.grpc.chat;

public final class Chat {
  private Chat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Chat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_chat_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_chat_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\025com.example.grpc.chat\"b\n\013C" +
      "hatMessage\022\016\n\006sender\030\001 \001(\t\022\017\n\007message\030\002 " +
      "\001(\t\022\021\n\treceiveId\030\003 \001(\t\022\014\n\004file\030\004 \001(\014\022\021\n\t" +
      "timestamp\030\005 \001(\t2h\n\013ChatService\022Y\n\013SendMe" +
      "ssage\022\".com.example.grpc.chat.ChatMessag" +
      "e\032\".com.example.grpc.chat.ChatMessage(\0010" +
      "\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_chat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_chat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_chat_ChatMessage_descriptor,
        new java.lang.String[] { "Sender", "Message", "ReceiveId", "File", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
