// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/proto/chat.proto
// Protobuf Java Version: 4.29.0

package com.example.grpc.chat;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.chat.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 발신자
   * </pre>
   *
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <pre>
   * 발신자
   * </pre>
   *
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <pre>
   * 메시지 내용
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 메시지 내용
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 메시지 전송 시간
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * 메시지 전송 시간
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
